{
 "title": "Internet Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Internet Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How is my Internet now?",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "internet_monitor_up" }
   ]
  },
  {
   "title": "Internet Download Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(internet_monitor_download_size_bytes / (rate(internet_monitor_download_duration_seconds_sum[15m])/rate(internet_monitor_download_duration_seconds_count[15m]))) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Averate RTT (Instant)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(internet_monitor_ping_latency_seconds_sum[5m])/rate(internet_monitor_ping_latency_seconds_count[5m])*1000"
    }
   ]
  },
  {
   "title": "ICMP Jitter (instant)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "targets": [
    { "expr": "internet_monitor_ping_jitter" }
   ]
  },
  { "title": "Internet Performance Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average RTT (ms)",
   "type": "graph",
   "description": "Shows Average RTT ICMP Echo request to 1.1.1.1 DNS servers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "RTT (ms)" }
   ],
   "targets": [
    {
     "expr": "rate(internet_monitor_ping_latency_seconds_sum[5m])/rate(internet_monitor_ping_latency_seconds_count[5m])*1000"
    }
   ]
  },
  {
   "title": "ICMP Jitter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "internet_monitor_ping_jitter" }
   ]
  },
  {
   "title": "Internet Download Speed (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "MB/s" }
   ],
   "targets": [
    {
     "expr": "(internet_monitor_download_size_bytes / (rate(internet_monitor_download_duration_seconds_sum[15m])/rate(internet_monitor_download_duration_seconds_count[15m]))) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Number of packet loss over ICMP request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "internet_monitor_ping_packet_loss"
    }
   ]
  },
  {
   "title": "Internet Availability",
   "type": "graph",
   "description": "Shows internet availability over time\nUP = 1\nDown = 0",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "UP=1 Down=0" }
   ],
   "targets": [
    { "expr": "internet_monitor_up" }
   ]
  },
  {
   "title": "Internet Monitor App Logs",
   "type": "logs",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{container_name=\"internet-monitor_im_1\"}"
    }
   ]
  }
 ]
}